### ISSUE TITLE
assessRecordNumber crash when no records dropped

### ISSUE THREAD

**Issue by GPowney** [robboyd/occAssess#11]
I had the folllowing error message when running [assessRecordNumber](https://github.com/robboyd/occAssess/blob/main/R/assessRecordNumber.R) on a insect occurrence dataset.

`Error in `$<-.data.frame`(`*tmp*`, "Period", value = NA) :  replacement has 1 row, data has 0`

I think this is because `dat` loses all records when `drop` is empty (line 17).  For context I set period `list(1970:1995, 1996:2016)`, so nothing is dropped (all years are included).

To recreate this issue try running this function on your data but choose period years that ensure `drop` is empty.

**Comment by robboyd** [comment]
Good spot. Have now fixed so that the piece of code that's drops data is only implemented if there is anything to drop
