### ISSUE TITLE
assessSpatialCov > unused argument in example

### ISSUE THREAD

**Issue by GPowney** [robboyd/occAssess#13]
The [Rpub vignette](https://rpubs.com/RobBoyd/726503), and the [assessSpatialCov](https://github.com/robboyd/occAssess/blob/main/R/assessSpatialCov.R) documentation suggests `periods` is required for the function, however, when testing I get the following response:

`Error in assessSpatialCov(dat = new_spatial_data, periods = ten_periods,  : 
  unused argument (periods = ten_periods)`

The function works if `periods = ten_periods` is removed from the call.

**Comment by robboyd** [comment]
Sorry @GPowney the vignette is now behind the code. Will publish a new one today

**Comment by GPowney** [comment]
Okay, nice one!
