### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by AugustT** [robboyd/occAssess#20]
Could you put some of your vignette into the readme so that someone visiting your page can see what it does and how it works? Also you could add Travis and CodeCov badges

**Comment by robboyd** [comment]
Yep can do. Have set travis up but it won't pass because of dependencies of dependencies - it's actually really annoying

**Comment by robboyd** [comment]
It does pass r cmd check

**Comment by AugustT** [comment]
You might need to tell Travis to install the dependencies before you start the tests, I seem to remember having to do this with another package

**Comment by AugustT** [comment]
See lines 8-35 here https://github.com/zoonproject/zoon/blob/master/.travis.yml

**Comment by robboyd** [comment]
Will try this cheers. Vignette now in the readme

**Comment by AugustT** [comment]
Jeeez, that was fast!

**Comment by AugustT** [comment]
readme updated
