### ISSUE TITLE
Periods displayed in wrong order when >= 10 periods

### ISSUE THREAD

**Issue by robboyd** [robboyd/occAssess#22]

**Comment by sacrevert** [comment]
This appears to have been fixed e.g. 
![image](https://github.com/robboyd/occAssess/assets/5985134/57fcbd52-1c0a-4123-bf86-438e70bf8fd8)

**Comment by sacrevert** [comment]
My bad, this does still happen
![image](https://github.com/robboyd/occAssess/assets/5985134/9bbcc7c1-a243-4e3b-9694-0423c7ea0ca1)

**Comment by sacrevert** [comment]
Now fixed for all functions, including `assessSpatialBias()`
