### ISSUE TITLE
assessSpatialCov with shp file 

### ISSUE THREAD

**Issue by linden-p** [robboyd/occAssess#43]
Can assessSpatialCov be used with a shapefile and how?

Thanks!

**Comment by sacrevert** [comment]
The [code](https://github.com/robboyd/occAssess/blob/master/R/assessSpatialCov.R) shows how the function works. If you mean that you have species distribution data in a shapefile, then you will need to turn this into a data frame containing x and y coordinates for your coordinate reference system. Presumably these will either be point locations, or centroids/corners of areal sites. Turning a shapefile of points into this type of data frame is pretty easy with standard GIS functions in R. For example, using functions in the `sf` library such as `sf::st_as_sf()` and `sf::st_coordinates()`

**Comment by robboyd** [comment]
Thanks mate
